### ISSUE TITLE
Could not load the 'Cloudformation' driver from the load path

### ISSUE THREAD

**Issue by whal3382** [neillturner/kitchen-cloudformation#7]
I know there has been an issue opened on this before but I am currently running into it again with Chef 4.0.60 and kitchen 2.2.5.
Steps:
Installed ChefDK rpm on an Amazon Linux instance.
chef gem install kitchen-cloudformation and get the following error:

WARNING:  You don't have /home/ec2-user/.chefdk/gem/ruby/2.6.0/bin in your PATH, gem executables will not run.

When using the example kitchen.yml provided I get the following error:

 ------Exception-------
 Class: Kitchen::ClientError
Message: Could not load the 'Cloudformation' driver from the load path. Did you mean: azurerm, digitalocean, dokken, dummy, ec2, exec, gce, hyperv, proxy, vagrant ? Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
 ----------------------
Please see .kitchen/logs/kitchen.log for more details
Also try running `kitchen diagnose --all` for configuration

Is there something that I am missing?
Thanks

**Comment by whal3382** [comment]
Fixed the path error by following the ruby environment configurations at https://docs.chef.io/chefdk_setup.html. Still having the could not load the Cloudformation driver error.

**Comment by cpoma** [comment]
If you do an install like: gem install --no-user-install <name of gem>
It will install the gem into the base ruby path versus putting it in a user-folder needing you to update the path. 
If you want it in the chef embedded Ruby (since your path is referencing ChefDK) something like:
/opt/chef-workstation/embedded/bin/gem install --no-user-install kitchen-cloudformation

**Comment by cpoma** [comment]
This error is related to aws-sdk-core-2.11.306 conflicts with aws-sdk-core (~> 3, >= 3.56.0). Most of the modules have updated to aws-sdk-core >= 3. This module still uses aws-sdk-core version 2. To get around this issue (not sure if this will break the functionality) do the following:

Update you PATH to include the Chef-Workstation \bin:
--
`
export PATH=/opt/chef-workstation/embedded/bin:$PATH
`

Update these modules and clean up gems:
---

```
/opt/chef-workstation/embedded/bin/gem install --no-user-install train-aws
/opt/chef-workstation/embedded/bin/gem install --no-user-install aws-sdk-cloudtrail
/opt/chef-workstation/embedded/bin/gem cleanup train-aws
/opt/chef-workstation/embedded/bin/gem cleanup aws-sdk-organizations
/opt/chef-workstation/embedded/bin/gem cleanup aws-sdk-autoscaling
```

Edit - /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/kitchen-cloudformation-1.5.0/kitchen-cloudformation.gemspec
---


```
#  gem.add_dependency 'aws-sdk', '~> 2'
  gem.add_dependency 'aws-sdk', '~>3', '>= 3.56.0'
```
Rebuilt it:
---

`opt/chef-workstation/embedded/bin/gem build /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/gems/kitchen-cloudformation-1.5.0/kitchen-cloudformation.gemspec`

Edit - /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/specifications/kitchen-cloudformation-1.5.0.gemspec
---

```
    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
#      s.add_runtime_dependency(%q<aws-sdk>.freeze, ["~> 2"])
      s.add_runtime_dependency(%q<aws-sdk>.freeze, ["~> 3"])
      s.add_runtime_dependency(%q<excon>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<multi_json>.freeze, [">= 0"])
      s.add_runtime_dependency(%q<retryable>.freeze, ["~> 2.0"])
      s.add_runtime_dependency(%q<test-kitchen>.freeze, [">= 1.4.1"])
    else
#      s.add_dependency(%q<aws-sdk>.freeze, ["~> 2"])
      s.add_dependency(%q<aws-sdk>.freeze, ["~> 3"])
      s.add_dependency(%q<excon>.freeze, [">= 0"])
      s.add_dependency(%q<multi_json>.freeze, [">= 0"])
      s.add_dependency(%q<retryable>.freeze, ["~> 2.0"])
      s.add_dependency(%q<test-kitchen>.freeze, [">= 1.4.1"])
    end
  else
#    s.add_dependency(%q<aws-sdk>.freeze, ["~> 2"])
    s.add_dependency(%q<aws-sdk>.freeze, ["~> 3"])
    s.add_dependency(%q<excon>.freeze, [">= 0"])
    s.add_dependency(%q<multi_json>.freeze, [">= 0"])
    s.add_dependency(%q<retryable>.freeze, ["~> 2.0"])
    s.add_dependency(%q<test-kitchen>.freeze, [">= 1.4.1"])
  end
end
```

Rebuild it:
---

`opt/chef-workstation/embedded/bin/gem build /opt/chef-workstation/embedded/lib/ruby/gems/2.6.0/specifications/kitchen-cloudformation-1.5.0.gemspec`


Create a sample kitchen.yml file:
---
```
verifier:
  name: inspec

driver:
  name: cloudformation
  stack_name: sample_stack
#  template_file: /test/example.template
#  parameters:
#    base_package: wget
#  change_set_name: mystack-cs
#  change_set_template_file: TestSecurityGroupCs.template

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://www.vagrantup.com/docs/networking/forwarded_ports.html

#  network:
#    - ["forwarded_port", {guest: 80, host: 8080}]

provisioner:
  name: cloudformation

  ## product_name and product_version specifies a specific Chef product and version to install.
  ## see the Chef documentation for more details: https://docs.chef.io/config_yml_kitchen.html
  #  product_name: chef
  #  product_version: 15

platforms:
  - name: rhel-7
    driver: cloudformation

suites:
  - name: default
    verifier:
      inspec_tests:
        - test/integration/default
    attributes:
```

Then, run `kitchen list`

[root@my_test_box cloudformation_sample]# kitchen list
```
Instance        Driver          Provisioner     Verifier  Transport  Last Action    Last Error
default-rhel-7  Cloudformation  Cloudformation  Inspec    Ssh        <Not Created>  <None>
```
